version: "3.9"

services:
  database_pets:
    image: postgres
    container_name: database_pets
    restart: always
    ports: 
      - 5432:5432
    environment:
      - POSTGRES_USER=thiago
      - POSTGRES_PASSWORD=lucy123
      - POSTGRES_DB=petsjournal
    volumes:
      - pgdata:/data/postgres


  app:
    build: .
    container_name: petsjournal
    restart: always
    ports: 
      - 3333:3333
      - 9229:9229
    volumes: 
      - .:/usr/app
      - /usr/app/node_modules
    links: 
      - database_pets
    depends_on:
      - database_pets



volumes:
  pgdata:
    driver: local